server:
  port: 0
spring:
  application:
    name: MSTxFleet-Location
  cloud:
    discovery:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


